nginx-proxy:
  image: jwilder/nginx-proxy
  restart: always
  ports:
    - "80:80"
    - "443:443"
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock:ro
    - ./nginx/certs:/etc/nginx/certs:ro
    - /etc/nginx/vhost.d
    - /usr/share/nginx/html

  labels:
    - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy

letsencrypt:
  image: jrcs/letsencrypt-nginx-proxy-companion
  restart: always
  volumes:
    - ./nginx/certs:/etc/nginx/certs
    - /var/run/docker.sock:/var/run/docker.sock:ro
  volumes_from:
    - nginx-proxy:rw

www:
  image: nginx
  restart: always
  expose:
    - "80"
  volumes:
    - /Users/estebanrfp/certs/1/www:/usr/share/nginx/html:ro
  environment:
    - VIRTUAL_HOST=radarprop.com,www.radarprop.com
    - LETSENCRYPT_HOST=radarprop.com,www.radarprop.com
    - LETSENCRYPT_EMAIL=admin@radarprop.com
